name: occusearch
description: OccuSearch - ANZSCO Search Tool

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.

version: 2.0.8+69

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Navigation
  go_router:
   git:
      url: git@github.com:dharmendrakumar4525/go_router_konze.git
      ref: main
  focus_detector: ^2.0.1

  # SVG, rive, Image picker, file picker etc
  flutter_svg: ^2.0.7
  rive: ^0.11.1
  cached_network_image: ^3.2.3
  file_picker: ^8.3.2
  cupertino_icons: ^1.0.6

  # State Management
  flutter_rx_bloc: ^5.0.2

  # Network, API & cache
  connectivity_plus: ^5.0.2
  dio: ^5.2.1+1
  dio_cache_interceptor_file_store: ^1.2.2
  dio_cache_interceptor: ^3.4.2

  # Database
  sqflite: ^2.2.8+4

  # Package & Device info
  uuid: ^4.4.2
  package_info_plus:
  android_id: ^0.4.0
  #android_id: ^0.1.3+1

  # firebase
  firebase_core: ^3.10.0
  firebase_remote_config: ^5.3.0
  firebase_database: ^11.3.0
  firebase_dynamic_links: ^6.1.0
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.4.2
  firebase_messaging: ^15.2.0
  firebase_analytics: ^11.4.0
  firebase_performance: ^0.10.1
  firebase_crashlytics: ^4.3.0

  # ** Share **
  share_plus: ^10.0.1

  # Webview
  webview_flutter: ^4.2.2

  # SignIn method
  google_sign_in: ^6.2.1
  the_apple_sign_in: ^1.1.1

  #  ** Loading shimmer **
  shimmer: ^2.0.0

  # local notifications
  flutter_local_notifications: ^18.0.1

  # Utility
  shared_preferences: ^2.1.2
  path_provider: ^2.0.15
  url_launcher: ^6.1.11
  flutter_secure_storage: ^8.0.0
  money_formatter: ^0.0.3
  device_info_plus: ^11.0.0
  lottie: ^2.4.0
  flutter_plugin_android_lifecycle: ^2.0.22
  animated_text_kit: ^4.2.2
  image_picker: ^1.0.0

  #  ** Graph Library **
  syncfusion_flutter_gauges: ^28.1.38
  syncfusion_flutter_charts: ^28.1.38

  #Slider
  syncfusion_flutter_sliders: ^28.1.38
  sleek_circular_slider: ^2.0.1

  #maps
  syncfusion_flutter_maps: ^28.1.38

  #Swipe Card
  card_swiper: ^2.0.4

  #Google Map
  google_maps_flutter: ^2.10.0

  #For getting user location
  geolocator: ^9.0.2
  geocoding: ^2.1.0

  #Scrolling Position
  scrollable_positioned_list: ^0.3.8

  # Permission
  permission_handler: ^11.0.0
  #permission_handler: ^10.2.0
  #permission_handler: ^6.1.3
  #permission_handler: ^7.2.0

  #  ** PDF generator **
  pdf: ^3.10.7
  printing: ^5.11.0

  #  ** HTML Widget **
  flutter_widget_from_html_core: ^0.10.1

  # In-app Update
  in_app_update: ^4.2.3

  flutter_screenutil: ^5.8.4

  # ** Facebook event **
  facebook_app_events: ^0.19.2

  # ** animations **
  flutter_staggered_animations: ^1.1.1

  #to convert html to string
  html_to_pdf_plus: ^1.0.6

  #  #to autofill received sms for OTP
  #  telephony: ^0.2.0

  #pdf viewer
  syncfusion_flutter_pdfviewer: ^28.1.38

  # In app purchase
  in_app_purchase: ^3.1.13
#  grpc: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/png/
    - assets/icons/svg/
    - assets/icons/webp/
    - assets/json/
    - assets/rive/
    - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: NotoBold
      fonts:
        - asset: assets/fonts/notosans-bold.ttf

    - family: NotoSemiBold
      fonts:
        - asset: assets/fonts/notosans-semibold.ttf

    - family: NotoLight
      fonts:
        - asset: assets/fonts/notosans-light.ttf

    - family: NotoMedium
      fonts:
        - asset: assets/fonts/notosans-medium.ttf

    - family: NotoRegular
      fonts:
        - asset: assets/fonts/notosans-regular.ttf

    - family: NotoItalic
      fonts:
        - asset: assets/fonts/notosans-italic.ttf

    - family: NotoThin
      fonts:
        - asset: assets/fonts/notosans-thin.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
